# Generated by Django 6.0 on 2025-12-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
        ),
    ]
